In [2]:
import pandas as pd
#a list of strings
x = ['Python','pandas']
#calling database interface list
df = pd.DataFrame(x)
print(df)

        0
0  Python
1  pandas


In [3]:
import pandas as pd
import numpy as np
a = pd.Series(['java','C','C++'])
a.map({'java':'Core'})

0    Core
1     NaN
2     NaN
dtype: object

In [1]:
import pandas as pd
import numpy as np
info = np.array(['P','a','n','d','a','s'])
a = pd.Series(info)
print(a)

0    P
1    a
2    n
3    d
4    a
5    s
dtype: object


In [4]:
s = pd.Series(['a','b','c'],
              name="vals")
s.to_frame()

vals
0    a
1    b
2    c

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
emp = ['vivek','hemant','neeraj','dev']
id  = [102,107,109,114]
emp_series = pd.Series(emp)
id_series =  pd.Series(id)
frame = {'Emp':emp_series,'ID':id_series}
result = pd.DataFrame(frame)
print(result)



      Emp   ID
0   vivek  102
1  hemant  107
2  neeraj  109
3     dev  114


In [10]:
import pandas as pd
dict = {'name':['smith','william','phill','parker'],
        'age':['28','39','34','36']}
info = pd.DataFrame(dict,index = [True,True,False,True])
print(info)

          name age
True     smith  28
True   william  39
False    phill  34
True    parker  36


In [11]:
import numpy as np
arr = np.arange(16)
print("the original array is:\n",arr)
arr = np.arange(16).reshape(2,8)
print("\nreshapedarray:\n",arr)
arr = np.arange(16).reshape(8,2)
print("\nreshaped array:\n",arr)

the original array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshapedarray:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshaped array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
